server:
  port: 9090
---
management:
    endpoints:
        web:
            exposure:
                include:
                    - "gateway"
    endpoint:
        gateway:
            enabled: true
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      enabled: true
      reload:
        enabled: false
      discovery:
        wait-cache-ready: false  
    gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: user-service
            uri: http://user
            predicates:
            - Path=/user/**
            filters:
            - RewritePath=/user/(?<path>.*),/$\{path}
            
          - id: account-service
            uri: http://account
            predicates:
            - Path=/account/**
            filters:
            - RewritePath=/account/(?<path>.*),/$\{path}

